### ISSUE TITLE
ResultPager issue

### ISSUE THREAD

**Issue by Stdubic** [GrahamCampbell/Laravel-GitLab#33] opened 2020-12-21 15:58 UTC
Hi guys.

I have an issue with ResultPager,  My code goes like this:

$client = new Client();
$pager = new ResultPager($client,20);
$issues = $pager->fetchAll($client->repositories(), 'commits', [11261183]);

and get back with the response array of all 700 commits not paged :(

Am I doing something wrong? Please help with this issue. Pagination is a must in my implementation of API.

**Comment by GrahamCampbell** [comment] 2020-12-21 16:11
Duplicate of https://github.com/GitLabPHP/Client/issues/610.

**Closed as completed by GrahamCampbell** 2020-12-21 16:11 UTC
